### ISSUE TITLE
Review delete behavior

### ISSUE THREAD

**Issue by ohernan** [RISCOSS/riscoss-corporate#106]
Delete button must ask for confirmation:
e.g. Are you sure that you want to delete entity [entity name]?

There is some things that cannot be removed, e.g. entities with children entities. In the test cases there are some details about what kind of thing can be removed (to be discussed). At least, we need a comprensible message when some object cannot be deleted.

**Comment by ohernan** [comment]
1.- The platform allaws ask for confirmation
2.- The system do not remove:
- layers with entities (issue #114)
- entities with risk sessions ?

**Comment by quim-motger** [comment]
In Layer Management, we need an exception message thrown when a layer cannot be deleted because it has associated entities.

We need to discuss if entities with risk sessions can be deleted or not.

**Comment by lidix91** [comment]
We cannot delete:
- Layers when there are entities belonging to this layer
- entities with risk sessions
- risk configurations with risk sessions
- models used in risk configurations

**Comment by lidix91** [comment]
to be decided: removing a model from a risk configuration that already has risk sessions
