### ISSUE TITLE
(SC-CEN-18) Printing of pages is not possible

### ISSUE THREAD

**Issue by ohernan** [RISCOSS/riscoss-corporate#117]
Bugs from TEI, 08.10.15 - n.9

**Comment by ohernan** [comment]
the user can use the "print" option in the popup menu, clicking on the left button.

**Comment by manolodd** [comment]
Of course. He/she also can take an screenshot :-). But It is expected a more "executive level" report

**Comment by albertosiena** [comment]
When we will sell a product we will think to this "executive level"; for now, it's far far beyond the scope of Riscoss

**Comment by quim-motger** [comment]
New feature for generating reports of a risk analysis session has been added. The results are shown as an HTML page in a new window. By printing the page as a pdf file, the results are printed as shown in the HTML page.
