### ISSUE TITLE
Redesing the Contextual inforamtion forms

### ISSUE THREAD

**Issue by ohernan** [RISCOSS/riscoss-corporate#132]
Posible solution:
- Not naming it as Contextual Information in the layers form, maybe "Layer Information"
- Allowing textual new fields. Maybe someone would like to keep the description and the URL for the entities. Althought they don't want to used in the models.
- Showing the "Layer Information" in the "Properties form" in the Entities form (first tab), just before the Parents/Children info. It is fixed
- Maintain the Contextual Information only for the Customised Information for the entity. Maybe named as "Customised Information".

related to #131

**Comment by ohernan** [comment]
mentioned in issue #131

**Comment by ohernan** [comment]
Do we want to allow using the models requeted information also when the user defines contextual information at the layer level?

**Comment by ohernan** [comment]
Alberto: I think it makes sense to have it also for layers

Btw, we should think whether it is the case to drop the entity page
and have only one configuration page in which the user can configure
everything from layers to entities; because now there is a sort of
duplication that requires double effort to maintain.

**Comment by quim-motger** [comment]
Contextual information is now decomposed in two different configurations:
- layer information, which can be configured from layer management and entity management, and it is shown in the properties tab
- custom information, which is shown per entity in a separated tab
