### ISSUE TITLE
Include all the entities as root nodes in th Entities Management form

### ISSUE THREAD

**Issue by ohernan** [RISCOSS/riscoss-corporate#141]
(TEI Requirement)

All the entities should appear as root in the tree. 

We need to duplicate the entity, placed as root and in the corresponding hierarchies depending on the parent/child links defined in it.

**Comment by quim-motger** [comment]
Two different views are now available:
- List view: all entities are shown in a list
- Tree view: all entities are shown in a tree structure showing hierarchy without repetitions

User can change from one view to another by clicking a button. Also, search method is available for both views. In the tree view, elements are shown as root nodes when searching.
