### ISSUE TITLE
the button why in the results does not appear always

### ISSUE THREAD

**Issue by lidix91** [RISCOSS/riscoss-corporate#145]
in some cases when the risk is not 0, this button does not appear

**Comment by albertosiena** [comment]
The why button appears for risks with exposure different from zero, and greater than a certain threshold (to exclude risks that are minimal).
But the threshold can be customized and reduced also to 0, if needed.

**Comment by lidix91** [comment]
What is the threshold in the current version? I don't know if we need to reduce it to 0, this is something to be decided by the use cases.
At some point it should be configurable.

**Comment by albertosiena** [comment]
Current threshold is 0.15
