### ISSUE TITLE
Overrided values in risk analysis results are hidden forever

### ISSUE THREAD

**Issue by manolodd** [RISCOSS/riscoss-corporate#148]
When you modify the input values both, for project (i.e. target_license) or in the components tab (i.e. the linking type) these fields are not editable again and are hidden. You cannot revert your overriding.

**Comment by lidix91** [comment]
Issue closed because it is duplicated, issue #126

**Comment by manolodd** [comment]
Sorry. I did a quick search before creating the issue but I did not see #126.
