### ISSUE TITLE
(SC-CEN-19) Radio indicators doesn't refresh always in what-if analysis

### ISSUE THREAD

**Issue by manolodd** [RISCOSS/riscoss-corporate#152]
Radio indicators doesn't refresh always in what-if analysis. Sometimes it is necessary to add several units of the same kind of license until the radio indocator widget "wakes up". It is something ramdom. Sometimes it happens and sometimes ti does not.

**Comment by lidix91** [comment]
It seems to be related with the fact that every time you change one value (one click on +/- buttons) the results are refreshed. The platform refreshing is slower than the user clicking.

Possible solutions:
- not refreshing after each click, having an "Apply" button. The user make the changes s/he needs, and then click on "Apply"
- Adding a "running..." label during the refreshing. This does not solve the problem but shows the user that the platform is busy

**Comment by manolodd** [comment]
I think that it sound better the second option. Choose the one that is more easier to implement, but if possible, try adding a "Running..." label.

**Comment by lidix91** [comment]
Fixed
