### ISSUE TITLE
Adding new parameter in Contextual Info but not deleting (SC-TEI-13)

### ISSUE THREAD

**Issue by teicrb** [RISCOSS/riscoss-corporate#154]
It is possible to add new parameter in Contextual Information but not delete anything. It is also possible to modify Data Collectors. It has not been possible to verify the point 4 (the only meaningful) of the use case SC-TEI-13: 4) The user verifies that all the parameters can be changed except the object id. As it is not possible to change the name at Entity level.

Please refer to Mariella and Arcangelo Antonio for further details.

**Comment by lidix91** [comment]
1.-Contextual Information:
I cannot reproduce this error. It seems a problem refresing the entities whent the user is adding "customised" contextual information in the entity form (see 1.b)

1.-The platform allows to add contextual information in 2 diffent ways:
1.a- From the Layer form: the contextual information can be deleted, selecting the contextual information in the list and using the delete button next to the list
1.b- From the Entity form: The user can define "Customized" contextual information specific for one layer filling the name/value fields. In this case, this information is created when the user clicks on the enter button and it can be deleted clicking in the character "-" next to the field to be deleted. In this case, it seems that the platform does not refresh after deleting the fields, if you change the entity and comes back the contextual information is deleted. 

The contextual information created in a layer cannot be delete in a concrete entity, the contextual information defined in a layer only can be deleted in the layer form, affecting all the entities associated to this layer
2.- datacollectors: OK
3.- all the parameters cannot be changed: issue #93

**Comment by teicrb** [comment]
Please , insted of clicking in the character "-" next to the field, use the same behaviour of Layer by means of Delete button
