### ISSUE TITLE
No message shown on Entity successful deleted (SC-TEI-37)

### ISSUE THREAD

**Issue by teicrb** [RISCOSS/riscoss-corporate#158]
If a Layer is without Entity it is successfully deleted and no information message is shown. If a Layer contains one or more Entities there is a warning message informing about the manually deletion of the associated entities; if the user proceeds a pop-up “Internal Server Error” is shown without removing anything.

N.B.: in way to delete a Layer it would be better to have the possibility to move before the contained Entities.

Please refer to Mariella and Arcangelo Antonio for further details

**Comment by lidix91** [comment]
Issue solved in milestone 0.5.2. The delete behaviour is reviewed: (see issue #106 for details)

It is not an error that the platform is not informing when something is deleted successfully. If you need this new functionality open a new "enhancenment" issue
