### ISSUE TITLE
Get some order for goals in the results page

### ISSUE THREAD

**Issue by ohernan** [RISCOSS/riscoss-corporate#17]
We should sort the goals according to the hierarchy, the roots first, the leafs after.

I don't know if risks have the same hierarchical view. In the future we could try to show the hierarchy in the results

**Comment by ohernan** [comment]
Added ~56 label

**Comment by ohernan** [comment]
Milestone removed

**Comment by lidix91** [comment]
maybe we need something similar to the risk results argumentation

**Comment by quim-motger** [comment]
Risk analysis session results (both goals and risks) are now shown in a hierarchical way, considering the entity hierarchy
