### ISSUE TITLE
(SC-CEN-16) - Incomplete way of modifying risk sessions

### ISSUE THREAD

**Issue by manolodd** [RISCOSS/riscoss-corporate#174]
It is possible to modify risk sessions partially. It is possible to change the correspondence between layers and models and, except this, only deletion is allowed. There are semantic differences between the concept of “risk session” as defined in the test case and “risk configuration” as implemented by RISCOSS platform. Also, again, no checking is done to assure that the models being used have the required data and can be applied.

**Comment by lidix91** [comment]
What is the issue?

**Comment by manolodd** [comment]
Risk-session in the Test Case is understood from the beginning as a mix of Risk Configuration and Risk Session. But in the platform is not the same. It is not a problem. But it should be possible:
- To modify RC name, description... (it is not possible).
- To modify RS name (it is not possible)

**Comment by lidix91** [comment]
A risk session in RISCOSS is the execution of the risk analysis for one entity using the models defined in one risk configuration.

If the user needs to modify the risk configuration (and s/he has rights). It must be done from Configuration/Risk Configurations and it will affect to all the new risk ressions using this configuration

For now is not possible to modify the risk session name, we can keep this issue for this new feature
