### ISSUE TITLE
(SC-CEN-19) - What if analysis is not completed

### ISSUE THREAD

**Issue by manolodd** [RISCOSS/riscoss-corporate#176]
The platform allows playing with the models to forecast what is going to happen under certain circumstances. However it does this independently of a given risk session and therefore the resulting data are not contextualized. It should be initialized using any kind of baseline (based on a risk session data) to allow comparing the real state and the potential one. Also, there are some UI problems: the radio indicator widgets does not refresh always when required. The what-if analysis is still very poor and does not compare the real/current risk exposure levels with the simulated one. For instance, no delta risk values are computed. Making a decision using this type of what-if analysis is very difficult. Its results are useless if one need to recreate all the project to test one change (imagine project composed by thousands components).

**Comment by lidix91** [comment]
this issue mention different things that are already reported in separate issues:
- comparing risk session results with some what-if: addressed by issue #108 
- radio indicators does not refresh properly: addressed by issue #152 
- comparing real risk exposure with simulated (using delta ratio): addressed by issue #108
