### ISSUE TITLE
The parent Layer cannot be changed; it is fixed once created

### ISSUE THREAD

**Issue by anicolo66** [RISCOSS/riscoss-corporate#181]
The parent Layer cannot be changed; it is fixed once created

**Comment by lidix91** [comment]
duplicated (#182)

**Comment by lidix91** [comment]
it is no duplicated, it refers to the parent for Layers, not for entities

**Comment by lidix91** [comment]
We are going to allow changing the parent layer only if there is no entity created for this layer
