### ISSUE TITLE
The parent Layer of an Entity cannot be changed; it is fixed once created

### ISSUE THREAD

**Issue by anicolo66** [RISCOSS/riscoss-corporate#182]
The parent Layer of an Entity cannot be changed; it is fixed once created

**Comment by lidix91** [comment]
Duplicated (#127)

**Comment by lidix91** [comment]
Referent to modify the Layer of an entity.

**Comment by lidix91** [comment]
We are going to allow to modify the layer of an entity when:
- the entity does not have parents and childrens (the hierarchy could be broken)
- there is no risk sessions associated to this entity (the risk session uses the layer to select the models to be used in the analysis)
