### ISSUE TITLE
Layer Contextual Information modify (from Entity management menu)

### ISSUE THREAD

**Issue by anicolo66** [RISCOSS/riscoss-corporate#188]
When a modify of a Contextual Information related to a Layer is performed in the Entities Management  this modify is not propagated to the Layer that will have that Contextual Information unchanged. It should not be possible to change Information that are inherited from the upper level.

**Comment by lidix91** [comment]
In the entities management is not able to modify the layer's contextual information. The  "Custom contextual information" is contextual information added only to the entity where it is created.
