### ISSUE TITLE
Modify of inputs in Risk Analisys Sessions

### ISSUE THREAD

**Issue by anicolo66** [RISCOSS/riscoss-corporate#191]
Modify of the Input Values in the saved Risk Analisys Session has effect only the first time (pressing Save & Run button).

**Comment by lidix91** [comment]
Are the risk exposure values or the Execution time what is not changed after the "Running label..." disappears.

**Comment by quim-motger** [comment]
Save button is now correctly performed and information is refreshed after changes are saved
