### ISSUE TITLE
Entities created appears duplicated in the list

### ISSUE THREAD

**Issue by anicolo66** [RISCOSS/riscoss-corporate#199]
The list of the created Entities shows the created ones more than once (they appear duplicated, also triplicated).
Not all the created Entities are shown in the list. Not even a paging is created.

![entities](https://cloud.githubusercontent.com/assets/16401949/12849404/c32e07fc-cc1f-11e5-88b9-179c2b6f07ef.JPG)

**Comment by quim-motger** [comment]
Tree widget listing entities does not reproduce this bug anymore - it is completely refreshed when filtering by search and no duplicated entries appear
