### ISSUE TITLE
Adding mitigation activities

### ISSUE THREAD

**Issue by ohernan** [RISCOSS/riscoss-corporate#34]
Sub tasks: 
- #43 preliminary inclusion

**Comment by ohernan** [comment]
Added ~56 label

**Comment by ohernan** [comment]
We need to refine the issue in order to have differents aspects that could be released in different versions

**Comment by ohernan** [comment]
mentioned in issue #43

**Comment by ohernan** [comment]
Added ~76 label

**Comment by quim-motger** [comment]
Already added and integrated in the risk session workflow
