### ISSUE TITLE
Adding feedback button

### ISSUE THREAD

**Issue by ohernan** [RISCOSS/riscoss-corporate#49]
Proposal: new option "Help us" that opens a form with some text and 2 feedback buttons. Something like:

Give us your opinion about RISCOSS [User Feedback button]

If you are an expert on risk analysis, you can help us also improving our risk models [Expert Feedback button]

If you want more information about the project, visit our web site at www.riscoss.eu

**Comment by ohernan** [comment]
Added ~54 label

**Comment by lidix91** [comment]
we provide 2 menu options
