### ISSUE TITLE
Restore pagination in entity list

### ISSUE THREAD

**Issue by ohernan** [RISCOSS/riscoss-corporate#92]

**Comment by ohernan** [comment]
With the kind of controls we are using in the corporate (tree), the pagination does not have sense. In fact, the idea is removing all pagination from lists

**Comment by ohernan** [comment]
Very bad idea. Lists are potentially long, in principle you can have 1000s of entities in the RDR. You may end up with network overload, slow and unreadable web page.

**Comment by ohernan** [comment]
Ok, we can think keeping it for lists (there is no so much lists now), for the trees I'm not sure, it would be depending on the tree control we use.

**Comment by ohernan** [comment]
Added ~56 ~54 labels

**Comment by ohernan** [comment]
Milestone removed

**Comment by quim-motger** [comment]
View #141
